format = """
[╭─](fg:240)\
[](#8E1F62)\
$username\
$hostname\
[](bg:#FE1381 fg:#8E1F62)\
$directory\
[](fg:#FE1381 bg:#F7A1BC)\
$git_branch\
$git_status\
[](fg:#F7A1BC bg:#FACFD9)\
$docker_context\
[](fg:#FACFD9)\
$fill\
[](fg:#444444)\
$status\
[](bg:#444444 fg:#74BDFF)\
$package\
[](bg:#74BDFF fg:#50A7FF)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
[](fg:#008FFF bg:#50A7FF)\
$time\
[](fg:#008FFF)
[╰─](fg:240)\
$character
"""


# Disable the blank line at the start of the prompt
# add_newline = false

[status]
style = "bold fg:#aa0000 bg:#444444"
format = "[ $symbol$status ]($style)"
disabled = false

[fill]
symbol = "─"
style = "fg:240"

[character]
success_symbol = "[＞](bold green)"
error_symbol = "[＞](bold red)"
vicmd_symbol = "[＞](bold green)"

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = false
style_user = "bg:#8E1F62"
style_root = "bg:#8E1F62"
format = '[$user ]($style)'

[hostname]
format = "[$hostname ]($style)"
style = "bg:#8E1F62"
ssh_only = true

[directory]
style = "bg:#FE1381"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = true

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:#50A7FF"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#FACFD9"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#50A7FF"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#50A7FF"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#F7A1BC"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#F7A1BC"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#50A7FF"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#50A7FF"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#50A7FF"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#50A7FF"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#50A7FF"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#50A7FF"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#50A7FF"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#008FFF"
format = "[ $time ]($style)"

[package]
format = "[ $symbol$version ]($style)"
style = "bg:#74BDFF fg:208"